<?php
/**
 * @file
 * Code for the RUC Pictures feature.
 */

include_once 'ruc_pictures.features.inc';

/**
 * Implements hook_migrate_api().
 */
function ruc_pictures_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'RUCMigrate' => array(
        'title' => t('RUCMigrate Imports'),
      ),
    ),
    'migrations' => array(
      'RUCPictureNode' => array('class_name' => 'RUCPictureNode', 'group_name' => 'RUCMigrate'),
    ),
  );

  return $api;
}
